---
- name: Ansible házi feladat
  hosts: all
  become: true

    # roles:
    #- nfs
    #- user
  tasks:

#nfs role tartalma:

    - name: Create shared directory
      file:
        path: "{{ nfs_shared_directory }}"
        state: directory
        mode: '0777'
      vars:
        nfs_shared_directory: /data/comp/

    - name: Install NFS server
      dnf:
        name: nfs-utils
        state: present

    - name: Configure NFS share
      lineinfile:
        path: /etc/exports
        line: "{{ nfs_share_line }}"
        state: present
        backup: yes
        create: yes
      vars:
        nfs_share_line: "{{ nfs_shared_directory }} *(rw,async,no_subtree_check,no_root_squash)"

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted
