    - name: Install nfs-utils package
      dnf:
        name: nfs-utils
        state: present

    - name: Create directory for NFS share
      file:
        path: "{{ nfs_share_dir }}"
        state: directory
        mode: '0777'

    - name: Add NFS export to /etc/exports
      lineinfile:
        path: /etc/exports
        line: "{{ nfs_share_dir }} {{ nfs_client }}(rw,sync)"
        state: present
        create: true
        
